### ISSUE TITLE
feat: radius for LinearProgressBar

### ISSUE THREAD

**Issue by nickf2k** [Angopapo/linear_progress_bar#1]
hi @maravilho, @maravilhosinga I used your package. It's great.
However, I think adding a radius to the LinearProgressBar would be a nice improvement, similar to this
![image](https://github.com/Angopapo/linear_progress_bar/assets/44032235/e7a4d386-9e42-4885-8fe4-63544537c498)
or this 
![image](https://github.com/Angopapo/linear_progress_bar/assets/44032235/30b7d032-e18c-4b56-bb91-4ff6d38b88b7)
Can I open a PR for this issue?

**Comment by maravilhosinga** [comment]
Hello, @nickf2k 
You can open PR.

I'm a little busy right now. I will make some updates when possible, but you are free to contribute.

**Comment by nickf2k** [comment]
@maravilhosinga I open a PR for this at here https://github.com/Angopapo/linear_progress_bar/pull/2
